### ISSUE TITLE
bug: fails to `init --setup`

### ISSUE THREAD

**Issue by vext01** [ArchiveBox/ArchiveBox#1018]
#### Describe the bug

Initialisation fails.

#### Steps to reproduce

 * Install from pip
 * run `archivebox init --setup` in a new directory.

#### Screenshots or log output

```
$ pip3.9 install archivebox
Defaulting to user installation because normal site-packages is not writeable
Collecting archivebox
...
Successfully installed archivebox-0.6.2
$ cd /tmp/b
$ ~/.local/bin/archivebox init --setup
[i] [2022-09-01 10:19:38] ArchiveBox v0.6.2: archivebox init --setup
    > /tmp/b

Traceback (most recent call last):
  File "/home/edd/.local/bin/archivebox", line 8, in <module>
    sys.exit(main())
  File "/home/edd/.local/lib/python3.9/site-packages/archivebox/cli/__init__.py", line 140, in main
    run_subcommand(
  File "/home/edd/.local/lib/python3.9/site-packages/archivebox/cli/__init__.py", line 74, in run_subcommand
    setup_django(in_memory_db=subcommand in fake_db, check_db=cmd_requires_db and not init_pending)
  File "/home/edd/.local/lib/python3.9/site-packages/archivebox/config.py", line 1136, in setup_django
    django.setup()
  File "/home/edd/.local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/edd/.local/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/edd/.local/lib/python3.9/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/home/edd/.local/lib/python3.9/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/edd/.local/lib/python3.9/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/edd/.local/lib/python3.9/site-packages/archivebox/core/admin.py", line 26, in <module>
    from config import OUTPUT_DIR, SNAPSHOTS_PER_PAGE
ImportError: cannot import name 'OUTPUT_DIR' from 'config' (/home/edd/.local/lib/python3.9/site-packages/config/__init__.py)
```

My guess: module name clash `config`. That is a very generic name. Will try in a virtualenv next.

#### ArchiveBox version

Latest from pip

**Comment by vext01** [comment]
Works in a virtualenv
