### ISSUE TITLE
Bug: "cannot create directory" during docker-compose run

### ISSUE THREAD

**Issue by llagerlof** [ArchiveBox/ArchiveBox#1076]
#### Describe the bug

As a normal user (not root) I tried to use the docker installation process, but failed. I already use docker in another projects. I am on Fedora 36, Gnome, bash.

#### Steps to reproduce

1. Create a directory `archivebox` and enter it.
2. Run `docker-compose run archivebox init --setup`
3. After some pulls I received some errors:

```
$ docker-compose run archivebox init --setup
Creating network "archivebox_default" with the default driver
Pulling archivebox (archivebox/archivebox:master)...
master: Pulling from archivebox/archivebox
f7ec5a41d630: Pull complete
388aab6f3954: Pull complete
f8d31dc90ab0: Pull complete
9d4ee0e5b63b: Pull complete
56f49306e49e: Pull complete
d2e40516d5a1: Pull complete
1a6c44aa9dfa: Pull complete
c4d35fef0055: Pull complete
5c4dbf4c13a7: Pull complete
45cb3b53e879: Pull complete
0f5eda0afe08: Pull complete
e2e79e5cb02f: Pull complete
3bd6f4ed69dd: Pull complete
7bc4dec320ca: Pull complete
4a89c4271f84: Pull complete
c01c00fb5d2e: Pull complete
96d240f09f68: Pull complete
3360d8b9cbe2: Pull complete
f322e41d2d58: Pull complete
91c6f527d4a5: Pull complete
69bc231c417e: Pull complete
71cd0966e9b1: Pull complete
Digest: sha256:c2e307bec25e7101709036117446feb080a0bf50397f148f4ee24807afe5e031
Status: Downloaded newer image for archivebox/archivebox:master
Creating archivebox_archivebox_run ... done
mkdir: cannot create directory ‘/data/logs’: Permission denied
chown: cannot read directory '/data': Permission denied
chown: changing ownership of '/data': Permission denied
[i] [2023-01-03 13:48:25] ArchiveBox v0.6.2: archivebox init --setup
    > /data

Traceback (most recent call last):
  File "/usr/local/bin/archivebox", line 33, in <module>
    sys.exit(load_entry_point('archivebox', 'console_scripts', 'archivebox')())
  File "/app/archivebox/cli/__init__.py", line 140, in main
    run_subcommand(
  File "/app/archivebox/cli/__init__.py", line 80, in run_subcommand
    module.main(args=subcommand_args, stdin=stdin, pwd=pwd)    # type: ignore
  File "/app/archivebox/cli/archivebox_init.py", line 43, in main
    init(
  File "/app/archivebox/util.py", line 114, in typechecked_function
    return func(*args, **kwargs)
  File "/app/archivebox/main.py", line 280, in init
    is_empty = not len(set(os.listdir(out_dir)) - ALLOWED_IN_OUTPUT_DIR)
PermissionError: [Errno 13] Permission denied: '/data'
ERROR: 1
```

#### ArchiveBox version

I could not provide this information because was an installation error, but the commit hash is d4c18e414261a5050bad2634441ef40d0619bb5d (from Dec 30, 2022).

**Comment by pirate** [comment]
Your data folder has the wrong permissions. `chmod -R 777 ./data` and re-run.

**Comment by llagerlof** [comment]
> Your data folder has the wrong permissions. `chmod -R 777 ./data` and re-run.

But this is my first run, and I don't even have a data folder. Should I create one? If yes, isn't explained in Quickstart section:
![image](https://user-images.githubusercontent.com/193798/210427110-6f8170d4-1cfe-45e0-b1b5-653f71d317f3.png)

**Comment by pirate** [comment]
This is a platform-specific issue that happens if your docker user is non-privileged on some OSs, because it's an edge case it's not explained in the Quickstart.

Create a data folder and chmod it 777 and it should work fine.

**Comment by llagerlof** [comment]
> that happens if your docker user is non-privileged on some OSs,

You are right. Well, I installed the pip version, and it's working fine. Thank you.

**Comment by marleyjaffe** [comment]
Is there a way to run the docker container as a specific user? I attempted adding `user: 1000:1000` to my docker-compose file but the error persists. I would prefer to not have my data dir fully open if possible. 

I updated my cifs mount fstab file to `//IP/ArchiveBox /mnt/ArchiveBox cifs uid=0,gid=0,credentials=smbcredentialsFILE,iocharset=utf8,file_mode=0777,dir_mode=0777 0 0` and properly see my mounted directory and all files owned by root:root & have 777 permissions but I am now see the below:

```
username@dockerserver:~/docker/archivebox$ sudo docker-compose run archivebox init --setup
sudo: unable to resolve host dockerserver: Name or service not known
[i] [2023-01-23 02:27:04] ArchiveBox v0.6.2: archivebox init --setup
    > /data

[+] Initializing a new ArchiveBox v0.6.2 collection...
----------------------------------------------------------------------

[+] Building archive folder structure...
    + ./archive, ./sources, ./logs...
    + ./ArchiveBox.conf...
Traceback (most recent call last):
  File "/usr/local/bin/archivebox", line 33, in <module>
    sys.exit(load_entry_point('archivebox', 'console_scripts', 'archivebox')())
  File "/app/archivebox/cli/__init__.py", line 140, in main
    run_subcommand(
  File "/app/archivebox/cli/__init__.py", line 80, in run_subcommand
    module.main(args=subcommand_args, stdin=stdin, pwd=pwd)    # type: ignore
  File "/app/archivebox/cli/archivebox_init.py", line 43, in main
    init(
  File "/app/archivebox/util.py", line 114, in typechecked_function
    return func(*args, **kwargs)
  File "/app/archivebox/main.py", line 320, in init
    write_config_file({}, out_dir=out_dir)
  File "/app/archivebox/config.py", line 498, in write_config_file
    atomic_write(config_path, CONFIG_HEADER)
  File "/app/archivebox/util.py", line 114, in typechecked_function
    return func(*args, **kwargs)
  File "/app/archivebox/system.py", line 96, in atomic_write
    os.chmod(path, int(OUTPUT_PERMISSIONS, base=8))
PermissionError: [Errno 1] Operation not permitted: '/data/ArchiveBox.conf'
username@dockerserver:~/docker/archivebox$ ll /mnt/ArchiveBox/
total 13K
drwxrwxrwx 2 root root    0 Jan 23 02:27 .
drwxr-xr-x 4 root root 4.0K Jan 23 00:58 ..
drwxrwxrwx 2 root root    0 Jan 23 02:27 archive
-rwxrwxrwx 1 root root  481 Jan 23 02:27 ArchiveBox.conf
-rwxrwxrwx 1 root root 6.1K Jan 23 01:03 .DS_Store
drwxrwxrwx 2 root root    0 Jan 23 02:27 logs
drwxrwxrwx 2 root root    0 Jan 23 02:27 sources
username@dockerserver:~/docker/archivebox$ sudo docker-compose run archivebox init --setup
sudo: unable to resolve host dockerserver: Name or service not known
Change in ownership detected, please be patient while we chown existing files
This could take some time...
[i] [2023-01-23 02:27:58] ArchiveBox v0.6.2: archivebox init --setup
    > /data

[+] Initializing a new ArchiveBox v0.6.2 collection...
----------------------------------------------------------------------

[+] Building archive folder structure...
    + ./archive, ./sources, ./logs...
    + ./ArchiveBox.conf...
Traceback (most recent call last):
  File "/usr/local/bin/archivebox", line 33, in <module>
    sys.exit(load_entry_point('archivebox', 'console_scripts', 'archivebox')())
  File "/app/archivebox/cli/__init__.py", line 140, in main
    run_subcommand(
  File "/app/archivebox/cli/__init__.py", line 80, in run_subcommand
    module.main(args=subcommand_args, stdin=stdin, pwd=pwd)    # type: ignore
  File "/app/archivebox/cli/archivebox_init.py", line 43, in main
    init(
  File "/app/archivebox/util.py", line 114, in typechecked_function
    return func(*args, **kwargs)
  File "/app/archivebox/main.py", line 320, in init
    write_config_file({}, out_dir=out_dir)
  File "/app/archivebox/config.py", line 505, in write_config_file
    atomic_write(f'{config_path}.bak', old.read())
  File "/app/archivebox/util.py", line 114, in typechecked_function
    return func(*args, **kwargs)
  File "/app/archivebox/system.py", line 96, in atomic_write
    os.chmod(path, int(OUTPUT_PERMISSIONS, base=8))
PermissionError: [Errno 1] Operation not permitted: '/data/ArchiveBox.conf.bak'
```

**Comment by pirate** [comment]
The root `/data` directory itself also needs `+x` permissions, not just the files within. ArchiveBox needs this to be able to create the `ArchiveBox.conf.bak` file.

**Comment by marleyjaffe** [comment]
when you say the dir needs `+x` permissions do you mean standard execute permissions or something else? The directory mounted has full 777  permissions applied to it. I'll try the `UID` and `GID` environment variables to see if that helps with anything.

```
username@dockerserver:~$ ls -laih /mnt
total 8.0K
          1048577 drwxr-xr-x  4 root   root   4.0K Jan 23 00:58 .
                2 drwxr-xr-x 19 root   root   4.0K Jan  7 18:36 ..
 3489708172640290 drwxrwxrwx  2 root   root      0 Jan 23 02:28 ArchiveBox
```
