### ISSUE TITLE
Bug: archivebox does not run in Python 3.12 with Django 3.1 due to removed 'distutils' package

### ISSUE THREAD

**Issue by aumars** [ArchiveBox/ArchiveBox#1308]
#### Describe the bug

archivebox does not run using Python 3.12 at because it uses Django 3.1 which requires [`distutils` which was removed from the standard library](https://peps.python.org/pep-0632/).

#### Steps to reproduce

Run archivebox in the terminal.

#### Screenshots or log output

```logs
$ archivebox
Traceback (most recent call last):
  File "/home/user/.local/bin/archivebox", line 5, in <module>
    from archivebox.cli import main
  File "/home/user/.local/pipx/venvs/archivebox/lib64/python3.12/site-packages/archivebox/cli/__init__.py", line 11, in <module>
    from ..config import OUTPUT_DIR, check_data_folder, check_migrations
  File "/home/user/.local/pipx/venvs/archivebox/lib64/python3.12/site-packages/archivebox/config.py", line 33, in <module>
    import django
  File "/home/user/.local/pipx/venvs/archivebox/lib64/python3.12/site-packages/django/__init__.py", line 1, in <module>
    from django.utils.version import get_version
  File "/home/user/.local/pipx/venvs/archivebox/lib64/python3.12/site-packages/django/utils/version.py", line 6, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'
```

#### ArchiveBox version
0.7.1

**Comment by pirate** [comment]
Yes it's not currently supported on 3.12, only 3.11.

I'm going to close this as it's not really a separate issue from upgrading Django: https://github.com/ArchiveBox/ArchiveBox/issues/988

Follow that issue for progress updates & discussion related to Python 3.12 + Django 4.
