### ISSUE TITLE
Sonic backend Error: ENDED authentication_failed doesn't contain protocol(NUMBER)Question: ...

### ISSUE THREAD

**Issue by iodrift** [ArchiveBox/ArchiveBox#1320]
I enabled the sonic search backend in my docker-compose.yml file, but I get `Error from the search backend, only showing results from default admin search fields - Error: ENDED authentication_failed doesn't contain protocol(NUMBER)` when I search.

Per related troubleshooting here I did the following:

```python
docker-compose run archivebox /usr/local/bin/python3
Creating archivebox_archivebox_run ... done
Python 3.11.7 (main, Dec  5 2023, 19:05:17) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> HOST = 'sonic'
>>> PORT = 1491
>>> with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
...     s.connect((HOST, PORT))
...     s.sendall(b'Hello, world')
...     data = s.recv(1024)
...
>>> print('Received', repr(data))
Received b'CONNECTED <sonic-server v1.4.8>'
>>> from sonic import SearchClient
>>> from archivebox.config import SEARCH_BACKEND_HOST_NAME, SEARCH_BACKEND_PORT, SEARCH_BACKEND_PASSWORD, SONIC_BUCKET, SONIC_COLLECTION
>>> with SearchClient(SEARCH_BACKEND_HOST_NAME, SEARCH_BACKEND_PORT, SEARCH_BACKEND_PASSWORD) as querycl:
...    print(querycl.query(SONIC_COLLECTION, SONIC_BUCKET, 'test'))
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.11/site-packages/sonic/client.py", line 661, in query
    return self._execute_command_async(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sonic/client.py", line 483, in _execute_command_async
    active = self.get_active_connection()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sonic/client.py", line 453, in get_active_connection
    active = self.pool.get_connection()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sonic/client.py", line 376, in get_connection
    conn = self._make_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sonic/client.py", line 398, in _make_connection
    con.connect()
  File "/usr/local/lib/python3.11/site-packages/sonic/client.py", line 219, in connect
    self.protocol = _parse_protocol_version(resp)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sonic/client.py", line 117, in _parse_protocol_version
    raise ValueError("{} doesn't contain protocol(NUMBER)".format(text))
ValueError: ENDED authentication_failed doesn't contain protocol(NUMBER)
>>> with SearchClient(SEARCH_BACKEND_HOST_NAME, SEARCH_BACKEND_PORT, SEARCH_BACKEND_PASSWORD) as querycl:
... print(querycl.query(SONIC_COLLECTION, SONIC_BUCKET, 'test'))
  File "<stdin>", line 2
    print(querycl.query(SONIC_COLLECTION, SONIC_BUCKET, 'test'))
    ^
IndentationError: expected an indented block after 'with' statement on line 1
>>> with SearchClient(SEARCH_BACKEND_HOST_NAME, SEARCH_BACKEND_PORT, SEARCH_BACKEND_PASSWORD) as querycl:
...     print(querycl.query(SONIC_COLLECTION, SONIC_BUCKET, 'test'))
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.11/site-packages/sonic/client.py", line 661, in query
    return self._execute_command_async(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sonic/client.py", line 483, in _execute_command_async
    active = self.get_active_connection()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sonic/client.py", line 453, in get_active_connection
    active = self.pool.get_connection()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sonic/client.py", line 376, in get_connection
    conn = self._make_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sonic/client.py", line 398, in _make_connection
    con.connect()
  File "/usr/local/lib/python3.11/site-packages/sonic/client.py", line 219, in connect
    self.protocol = _parse_protocol_version(resp)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sonic/client.py", line 117, in _parse_protocol_version
    raise ValueError("{} doesn't contain protocol(NUMBER)".format(text))
ValueError: ENDED authentication_failed doesn't contain protocol(NUMBER)
>>> exit()
```

This is my docker-compose.yml in pertinent part:

```docker-compose.yml
version: '3.9'

services:
    archivebox:
        # image: ${DOCKER_IMAGE:-archivebox/archivebox:dev}
        image: archivebox/archivebox:dev
        restart: always
        command: server --quick-init 0.0.0.0:8000
        ports:
            - 8000:8000
        volumes:
            - ./data:/data
#            - ./etc/crontabs:/var/spool/cron/crontabs  # uncomment this and archivebox_scheduler below to set up automatic recurring archive jobs
            # - ./archivebox:/app/archivebox             # uncomment this to mount the ArchiveBox source code at runtime (for developers working on archivebox)
        # build: .                                   # uncomment this to build the image from source code at buildtime (for developers working on archivebox)
        environment:
            - ALLOWED_HOSTS=*                       # restrict this to only accept incoming traffic via specific domain name
            - PUBLIC_INDEX=False                    # set to False to prevent anonymous users from viewing snapshot list
            - PUBLIC_SNAPSHOTS=False                # set to False to prevent anonymous users from viewing snapshot content
            - PUBLIC_ADD_VIEW=False                 # set to True to allow anonymous users to submit new URLs to archive
            - ADMIN_USERNAME=sij                    # create an admin user on first run with the given user/pass combo
            - ADMIN_PASSWORD=REDACTED
            - PUID=1000                            # set to your host user's UID & GID if you encounter permissions issues
            - PGID=1000
            - SEARCH_BACKEND_ENGINE=sonic           # uncomment these and sonic container below for better full-text search
            - SEARCH_BACKEND_HOST_NAME=sonic
            - SEARCH_BACKEND_PASSWORD=REDACTED
            - MEDIA_MAX_SIZE=4000m                  # increase this filesize limit to allow archiving larger audio/video files
            # - TIMEOUT=120                          # increase this number to 120+ seconds if you see many slow downloads timing out
            # - CHECK_SSL_VALIDITY=True              # set to False to disable strict SSL checking (allows saving URLs w/ broken certs)
            - SAVE_ARCHIVE_DOT_ORG=False            # set to False to disable submitting all URLs to Archive.org when archiving
            # ...
            # add further configuration options from archivebox/config.py as needed (to apply them only to this container)
            # or set using `docker compose run archivebox config --set SOME_KEY=someval` (to persist config across all containers)

        # For ad-blocking during archiving, uncomment this section and pihole service section below
#        networks:
#            - dns
#        dns:
#            - 172.35.0.53

    sonic:
        image: valeriansaliou/sonic:latest
        restart: always
        expose:
            - 1491
        environment:
            - SEARCH_BACKEND_PASSWORD=REDACTED
        volumes:
            - ./sonic.cfg:/etc/sonic.cfg:ro
            - ./data/sonic:/var/lib/sonic/store

#networks:
    # network needed for pihole container to offer :53 dns resolving on fixed ip for archivebox container
 #   dns:
 #       ipam:
 #           driver: default
 #           config:
 #               - subnet: 172.35.0.0/24
```

**Comment by pirate** [comment]
Please post the full output of `docker compose run archivebox version`.

Also try with `valeriansaliou/sonic:1.4.7` ([or an even earlier version](https://github.com/valeriansaliou/sonic/releases), as they have been having issues with arm64 builds recently.

**Comment by iodrift** [comment]
@pirate 

```docker-compose run archivebox version
Creating archivebox_archivebox_run ... done
0.7.1
ArchiveBox v0.7.1+editable BUILD_TIME=2023-12-18 06:57:51 1702882671
IN_DOCKER=True IN_QEMU=False ARCH=x86_64 OS=Linux PLATFORM=Linux-6.1.0-17-amd64-x86_64-with-glibc2.36 PYTHON=Cpython
FS_ATOMIC=True FS_REMOTE=True FS_USER=1000:1000 FS_PERMS=644
DEBUG=False IS_TTY=True TZ=UTC SEARCH_BACKEND=sonic LDAP=False

[i] Dependency versions:
 √  PYTHON_BINARY         v3.11.7         valid     /usr/local/bin/python3.11
 √  SQLITE_BINARY         v2.6.0          valid     /usr/local/lib/python3.11/sqlite3/dbapi2.py
 √  DJANGO_BINARY         v3.1.14         valid     /usr/local/lib/python3.11/site-packages/django/__init__.py
 √  ARCHIVEBOX_BINARY     v0.7.1          valid     /usr/local/bin/archivebox

 √  CURL_BINARY           v8.4.0          valid     /usr/bin/curl
 √  WGET_BINARY           v1.21.3         valid     /usr/bin/wget
 √  NODE_BINARY           v21.4.0         valid     /usr/bin/node
 √  SINGLEFILE_BINARY     v1.1.18         valid     /app/node_modules/single-file-cli/single-file
 √  READABILITY_BINARY    v0.0.9          valid     /app/node_modules/readability-extractor/readability-extractor
 √  MERCURY_BINARY        v1.0.0          valid     /app/node_modules/@postlight/parser/cli.js
 √  GIT_BINARY            v2.39.2         valid     /usr/bin/git
 √  YOUTUBEDL_BINARY      v2023.11.16     valid     /usr/local/bin/yt-dlp
 √  CHROME_BINARY         v120.0.6099.28  valid     /usr/bin/chromium-browser
 √  RIPGREP_BINARY        v13.0.0         valid     /usr/bin/rg

[i] Source-code locations:
 √  PACKAGE_DIR           24 files        valid     /app/archivebox
 √  TEMPLATES_DIR         4 files         valid     /app/archivebox/templates
 -  CUSTOM_TEMPLATES_DIR  -               disabled  None

[i] Secrets locations:
 -  CHROME_USER_DATA_DIR  -               disabled  None
 -  COOKIES_FILE          -               disabled  None

[i] Data locations:
 √  OUTPUT_DIR            7 files @       valid     /data
 √  SOURCES_DIR           163 files       valid     ./sources
 √  LOGS_DIR              1 files         valid     ./logs
 √  ARCHIVE_DIR           1334 files      valid     ./archive
 √  CONFIG_FILE           81.0 Bytes      valid     ./ArchiveBox.conf
 √  SQL_INDEX             14.8 MB         valid     ./index.sqlite3
```

Sonic v.1.4.7, or 1.4.0m didn't make a difference.

**Comment by pirate** [comment]
Strange, I don't see anything that looks wrong at first glance. Can you post your `sonic.cfg` file?

And maybe the output of `docker compose logs sonic` too.

**Comment by iodrift** [comment]
```sonic.cfg
# Sonic
# Fast, lightweight and schema-less search backend
# Configuration file
# Example: https://github.com/valeriansaliou/sonic/blob/master/config.cfg


[server]

log_level = "warn"


[channel]

inet = "0.0.0.0:1491"
tcp_timeout = 300

auth_password = "${env.SEARCH_BACKEND_PASSWORD}"

[channel.search]

query_limit_default = 65535
query_limit_maximum = 65535
query_alternates_try = 10

suggest_limit_default = 5
suggest_limit_maximum = 20


[store]

[store.kv]

path = "/var/lib/sonic/store/kv/"

retain_word_objects = 100000

[store.kv.pool]

inactive_after = 1800

[store.kv.database]

flush_after = 900

compress = true
parallelism = 2
max_files = 100
max_compactions = 1
max_flushes = 1
write_buffer = 16384
write_ahead_log = true

[store.fst]

path = "/var/lib/sonic/store/fst/"

[store.fst.pool]

inactive_after = 300

[store.fst.graph]

consolidate_after = 180

max_size = 2048
max_words = 250000
```


```
docker-compose logs sonic
Attaching to archivebox_sonic_1

```

**Comment by pirate** [comment]
can you change `log_level = "debug"` in `sonic.cfg`, and see what the `docker compose logs sonic` output is while you do this test:

```python3
...
>>> with SearchClient(SEARCH_BACKEND_HOST_NAME, SEARCH_BACKEND_PORT, SEARCH_BACKEND_PASSWORD) as querycl:
...     print(querycl.query(SONIC_COLLECTION, SONIC_BUCKET, 'test'))
```

**Comment by iodrift** [comment]
@pirate 

```logs
docker-compose logs sonic
Attaching to
```

``` test in archivebox
docker-compose run archivebox /usr/local/bin/python3
Creating network "archivebox_default" with the default driver
Creating archivebox_archivebox_run ... done
Python 3.11.7 (main, Dec  5 2023, 19:05:17) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> with SearchClient(SEARCH_BACKEND_HOST_NAME, SEARCH_BACKEND_PORT, SEARCH_BACKEND_PASSWORD) as querycl:
...     print(querycl.query(SONIC_COLLECTION, SONIC_BUCKET, 'test'))
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'SearchClient' is not defined
>>>     exit()
  File "<stdin>", line 1
    exit()
IndentationError: unexpected indent
>>> exit()
^C
^C^CERROR: Aborting.
```

```in sonic logs
docker-compose run sonic /usr/local/bin/python3
Creating archivebox_sonic_run ... done
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/local/bin/python3": stat /usr/local/bin/python3: no such file or directory: unknown
ERROR: 1
```

```testing logs again
docker-compose logs sonic
Attaching to
```

**Comment by pirate** [comment]
Sorry to clarify I meant do the test the same way you did above (+ set `log_level = "debug"` in `sonic.cfg`):

```python3
docker compose down

docker compose up sonic

docker compose run archivebox shell

>>> from sonic import SearchClient
>>> from archivebox.config import SEARCH_BACKEND_PASSWORD

>>>  with SearchClient('sonic', 1491, SEARCH_BACKEND_PASSWORD) as sc:
...     print(sc.query('archivebox', 'snapshots', 'test'))

**Comment by iodrift** [comment]
Ahh, gotcha--

```ArchiveBox Shell
[i] Welcome to the ArchiveBox Shell!
    https://github.com/ArchiveBox/ArchiveBox/wiki/Usage#Shell-Usage

    Hint: Example use:
        print(Snapshot.objects.filter(is_archived=True).count())
        Snapshot.objects.get(url="https://example.com").as_json()
        add("https://example.com/some/new/url")

In [1]: from sonic import SearchClient

In [2]: from archivebox.config import SEARCH_BACKEND_PASSWORD

In [3]: with SearchClient('sonic', 1491, SEARCH_BACKEND_PASSWORD) as sc:
   ...:     print(sc.query('archivebox', 'snapshots', 'test'))
   ...:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[3], line 2
      1 with SearchClient('sonic', 1491, SEARCH_BACKEND_PASSWORD) as sc:
----> 2     print(sc.query('archivebox', 'snapshots', 'test'))

File /usr/local/lib/python3.11/site-packages/sonic/client.py:661, in SearchClient.query(self, collection, bucket, terms, limit, offset, lang)
    658 offset = "OFFSET({})".format(offset) if offset else ''
    660 terms = quote_text(terms)
--> 661 return self._execute_command_async(
    662     'QUERY', collection, bucket, terms, limit, offset, lang)

File /usr/local/lib/python3.11/site-packages/sonic/client.py:483, in SonicClient._execute_command_async(self, cmd, *args)
    473 def _execute_command_async(self, cmd, *args):
    474     """Executes async command `cmd` with arguments `args` and awaits its result.
    475
    476     Arguments:
   (...)
    480         str|object -- result of execution
    481     """
--> 483     active = self.get_active_connection()
    484     try:
    485         active._execute_command(cmd, *args)

File /usr/local/lib/python3.11/site-packages/sonic/client.py:453, in SonicClient.get_active_connection(self)
    447 def get_active_connection(self) -> SonicConnection:
    448     """Gets a connection from the pool
    449
    450     Returns:
    451         SonicConnection -- connection from the pool
    452     """
--> 453     active = self.pool.get_connection()
    454     active.raw = self.raw
    455     return active

File /usr/local/lib/python3.11/site-packages/sonic/client.py:376, in ConnectionPool.get_connection(self)
    373     conn = self._available_connections.get()
    374 else:
    375     # make connection and add to active connections
--> 376     conn = self._make_connection()
    378 self._inuse_connections.add(conn)
    379 return conn

File /usr/local/lib/python3.11/site-packages/sonic/client.py:398, in ConnectionPool._make_connection(self)
    392 """Creates SonicConnection object and returns it.
    393
    394 Returns:
    395     SonicConnection -- newly created sonic connection.
    396 """
    397 con = SonicConnection(**self._create_kwargs)
--> 398 con.connect()
    399 return con

File /usr/local/lib/python3.11/site-packages/sonic/client.py:219, in SonicConnection.connect(self)
    216     self.connected = True
    218 resp = self._execute_command("START", self.channel, self._password)
--> 219 self.protocol = _parse_protocol_version(resp)
    220 self.bufsize = _parse_buffer_size(resp)
    222 return self.ping()

File /usr/local/lib/python3.11/site-packages/sonic/client.py:117, in _parse_protocol_version(text)
    115 matches = re.findall("protocol\((\w+)\)", text)
    116 if not matches:
--> 117     raise ValueError("{} doesn't contain protocol(NUMBER)".format(text))
    118 return matches[0]

ValueError: ENDED authentication_failed doesn't contain protocol(NUMBER)

```


```sonic logs
docker-compose up sonic
Creating network "archivebox_default" with the default driver
Creating archivebox_sonic_1 ... done
Attaching to archivebox_sonic_1
sonic_1       | (INFO) - starting up
sonic_1       | (INFO) - started
sonic_1       | (DEBUG) - spawn managed thread: tasker
sonic_1       | (DEBUG) - spawn managed thread: channel
sonic_1       | (INFO) - tasker is now active
sonic_1       | (INFO) - listening on tcp://0.0.0.0:1491
sonic_1       | (DEBUG) - running a tasker tick...
sonic_1       | (DEBUG) - scanning for kv store pool items to janitor
sonic_1       | (INFO) - done scanning for kv store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for fst store pool items to janitor
sonic_1       | (INFO) - done scanning for fst store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for kv store pool items to flush to disk
sonic_1       | (INFO) - no kv store pool items need to be flushed at the moment
sonic_1       | (DEBUG) - scanning for fst store pool items to consolidate
sonic_1       | (INFO) - no fst store pool items to consolidate in register
sonic_1       | (INFO) - ran tasker tick (took 0s + 1ms)
sonic_1       | (DEBUG) - running a tasker tick...
sonic_1       | (DEBUG) - scanning for kv store pool items to janitor
sonic_1       | (INFO) - done scanning for kv store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for fst store pool items to janitor
sonic_1       | (INFO) - done scanning for fst store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for kv store pool items to flush to disk
sonic_1       | (INFO) - no kv store pool items need to be flushed at the moment
sonic_1       | (DEBUG) - scanning for fst store pool items to consolidate
sonic_1       | (INFO) - no fst store pool items to consolidate in register
sonic_1       | (INFO) - ran tasker tick (took 0s + 0ms)
sonic_1       | (DEBUG) - running a tasker tick...
sonic_1       | (DEBUG) - scanning for kv store pool items to janitor
sonic_1       | (INFO) - done scanning for kv store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for fst store pool items to janitor
sonic_1       | (INFO) - done scanning for fst store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for kv store pool items to flush to disk
sonic_1       | (INFO) - no kv store pool items need to be flushed at the moment
sonic_1       | (DEBUG) - scanning for fst store pool items to consolidate
sonic_1       | (INFO) - no fst store pool items to consolidate in register
sonic_1       | (INFO) - ran tasker tick (took 0s + 0ms)
sonic_1       | (DEBUG) - running a tasker tick...
sonic_1       | (DEBUG) - scanning for kv store pool items to janitor
sonic_1       | (INFO) - done scanning for kv store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for fst store pool items to janitor
sonic_1       | (INFO) - done scanning for fst store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for kv store pool items to flush to disk
sonic_1       | (INFO) - no kv store pool items need to be flushed at the moment
sonic_1       | (DEBUG) - scanning for fst store pool items to consolidate
sonic_1       | (INFO) - no fst store pool items to consolidate in register
sonic_1       | (INFO) - ran tasker tick (took 0s + 0ms)
sonic_1       | (DEBUG) - running a tasker tick...
sonic_1       | (DEBUG) - scanning for kv store pool items to janitor
sonic_1       | (INFO) - done scanning for kv store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for fst store pool items to janitor
sonic_1       | (INFO) - done scanning for fst store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for kv store pool items to flush to disk
sonic_1       | (INFO) - no kv store pool items need to be flushed at the moment
sonic_1       | (DEBUG) - scanning for fst store pool items to consolidate
sonic_1       | (INFO) - no fst store pool items to consolidate in register
sonic_1       | (INFO) - ran tasker tick (took 0s + 0ms)
sonic_1       | (DEBUG) - running a tasker tick...
sonic_1       | (DEBUG) - scanning for kv store pool items to janitor
sonic_1       | (INFO) - done scanning for kv store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for fst store pool items to janitor
sonic_1       | (INFO) - done scanning for fst store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for kv store pool items to flush to disk
sonic_1       | (INFO) - no kv store pool items need to be flushed at the moment
sonic_1       | (DEBUG) - scanning for fst store pool items to consolidate
sonic_1       | (INFO) - no fst store pool items to consolidate in register
sonic_1       | (INFO) - ran tasker tick (took 0s + 0ms)
sonic_1       | (DEBUG) - running a tasker tick...
sonic_1       | (DEBUG) - scanning for kv store pool items to janitor
sonic_1       | (INFO) - done scanning for kv store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for fst store pool items to janitor
sonic_1       | (INFO) - done scanning for fst store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for kv store pool items to flush to disk
sonic_1       | (INFO) - no kv store pool items need to be flushed at the moment
sonic_1       | (DEBUG) - scanning for fst store pool items to consolidate
sonic_1       | (INFO) - no fst store pool items to consolidate in register
sonic_1       | (INFO) - ran tasker tick (took 0s + 0ms)
sonic_1       | (DEBUG) - running a tasker tick...
sonic_1       | (DEBUG) - scanning for kv store pool items to janitor
sonic_1       | (INFO) - done scanning for kv store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for fst store pool items to janitor
sonic_1       | (INFO) - done scanning for fst store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for kv store pool items to flush to disk
sonic_1       | (INFO) - no kv store pool items need to be flushed at the moment
sonic_1       | (DEBUG) - scanning for fst store pool items to consolidate
sonic_1       | (INFO) - no fst store pool items to consolidate in register
sonic_1       | (INFO) - ran tasker tick (took 0s + 0ms)
sonic_1       | (DEBUG) - running a tasker tick...
sonic_1       | (DEBUG) - scanning for kv store pool items to janitor
sonic_1       | (INFO) - done scanning for kv store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for fst store pool items to janitor
sonic_1       | (INFO) - done scanning for fst store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for kv store pool items to flush to disk
sonic_1       | (INFO) - no kv store pool items need to be flushed at the moment
sonic_1       | (DEBUG) - scanning for fst store pool items to consolidate
sonic_1       | (INFO) - no fst store pool items to consolidate in register
sonic_1       | (INFO) - ran tasker tick (took 0s + 0ms)
sonic_1       | (DEBUG) - running a tasker tick...
sonic_1       | (DEBUG) - scanning for kv store pool items to janitor
sonic_1       | (INFO) - done scanning for kv store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for fst store pool items to janitor
sonic_1       | (INFO) - done scanning for fst store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for kv store pool items to flush to disk
sonic_1       | (INFO) - no kv store pool items need to be flushed at the moment
sonic_1       | (DEBUG) - scanning for fst store pool items to consolidate
sonic_1       | (INFO) - no fst store pool items to consolidate in register
sonic_1       | (INFO) - ran tasker tick (took 0s + 0ms)
sonic_1       | (DEBUG) - running a tasker tick...
sonic_1       | (DEBUG) - scanning for kv store pool items to janitor
sonic_1       | (INFO) - done scanning for kv store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for fst store pool items to janitor
sonic_1       | (INFO) - done scanning for fst store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for kv store pool items to flush to disk
sonic_1       | (INFO) - no kv store pool items need to be flushed at the moment
sonic_1       | (DEBUG) - scanning for fst store pool items to consolidate
sonic_1       | (INFO) - no fst store pool items to consolidate in register
sonic_1       | (INFO) - ran tasker tick (took 0s + 0ms)
sonic_1       | (DEBUG) - running a tasker tick...
sonic_1       | (DEBUG) - scanning for kv store pool items to janitor
sonic_1       | (INFO) - done scanning for kv store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for fst store pool items to janitor
sonic_1       | (INFO) - done scanning for fst store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for kv store pool items to flush to disk
sonic_1       | (INFO) - no kv store pool items need to be flushed at the moment
sonic_1       | (DEBUG) - scanning for fst store pool items to consolidate
sonic_1       | (INFO) - no fst store pool items to consolidate in register
sonic_1       | (INFO) - ran tasker tick (took 0s + 0ms)
sonic_1       | (DEBUG) - running a tasker tick...
sonic_1       | (DEBUG) - scanning for kv store pool items to janitor
sonic_1       | (INFO) - done scanning for kv store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for fst store pool items to janitor
sonic_1       | (INFO) - done scanning for fst store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for kv store pool items to flush to disk
sonic_1       | (INFO) - no kv store pool items need to be flushed at the moment
sonic_1       | (DEBUG) - scanning for fst store pool items to consolidate
sonic_1       | (INFO) - no fst store pool items to consolidate in register
sonic_1       | (INFO) - ran tasker tick (took 0s + 0ms)
sonic_1       | (DEBUG) - channel client connecting: 172.29.0.3:37058
sonic_1       | (DEBUG) - got mode response: search
sonic_1       | (INFO) - password provided, but does not match
sonic_1       | (DEBUG) - running a tasker tick...
sonic_1       | (DEBUG) - scanning for kv store pool items to janitor
sonic_1       | (INFO) - done scanning for kv store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for fst store pool items to janitor
sonic_1       | (INFO) - done scanning for fst store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for kv store pool items to flush to disk
sonic_1       | (INFO) - no kv store pool items need to be flushed at the moment
sonic_1       | (DEBUG) - scanning for fst store pool items to consolidate
sonic_1       | (INFO) - no fst store pool items to consolidate in register
sonic_1       | (INFO) - ran tasker tick (took 0s + 0ms)
sonic_1       | (DEBUG) - running a tasker tick...
sonic_1       | (DEBUG) - scanning for kv store pool items to janitor
sonic_1       | (INFO) - done scanning for kv store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for fst store pool items to janitor
sonic_1       | (INFO) - done scanning for fst store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for kv store pool items to flush to disk
sonic_1       | (INFO) - no kv store pool items need to be flushed at the moment
sonic_1       | (DEBUG) - scanning for fst store pool items to consolidate
sonic_1       | (INFO) - no fst store pool items to consolidate in register
sonic_1       | (INFO) - ran tasker tick (took 0s + 0ms)
sonic_1       | (DEBUG) - running a tasker tick...
sonic_1       | (DEBUG) - scanning for kv store pool items to janitor
sonic_1       | (INFO) - done scanning for kv store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for fst store pool items to janitor
sonic_1       | (INFO) - done scanning for fst store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for kv store pool items to flush to disk
sonic_1       | (INFO) - no kv store pool items need to be flushed at the moment
sonic_1       | (DEBUG) - scanning for fst store pool items to consolidate
sonic_1       | (INFO) - no fst store pool items to consolidate in register
sonic_1       | (INFO) - ran tasker tick (took 0s + 0ms)
sonic_1       | (DEBUG) - running a tasker tick...
sonic_1       | (DEBUG) - scanning for kv store pool items to janitor
sonic_1       | (INFO) - done scanning for kv store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for fst store pool items to janitor
sonic_1       | (INFO) - done scanning for fst store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for kv store pool items to flush to disk
sonic_1       | (INFO) - no kv store pool items need to be flushed at the moment
sonic_1       | (DEBUG) - scanning for fst store pool items to consolidate
sonic_1       | (INFO) - no fst store pool items to consolidate in register
sonic_1       | (INFO) - ran tasker tick (took 0s + 0ms)
sonic_1       | (DEBUG) - running a tasker tick...
sonic_1       | (DEBUG) - scanning for kv store pool items to janitor
sonic_1       | (INFO) - done scanning for kv store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for fst store pool items to janitor
sonic_1       | (INFO) - done scanning for fst store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for kv store pool items to flush to disk
sonic_1       | (INFO) - no kv store pool items need to be flushed at the moment
sonic_1       | (DEBUG) - scanning for fst store pool items to consolidate
sonic_1       | (INFO) - no fst store pool items to consolidate in register
sonic_1       | (INFO) - ran tasker tick (took 0s + 0ms)
sonic_1       | (DEBUG) - running a tasker tick...
sonic_1       | (DEBUG) - scanning for kv store pool items to janitor
sonic_1       | (INFO) - done scanning for kv store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for fst store pool items to janitor
sonic_1       | (INFO) - done scanning for fst store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for kv store pool items to flush to disk
sonic_1       | (INFO) - no kv store pool items need to be flushed at the moment
sonic_1       | (DEBUG) - scanning for fst store pool items to consolidate
sonic_1       | (INFO) - no fst store pool items to consolidate in register
sonic_1       | (INFO) - ran tasker tick (took 0s + 0ms)
sonic_1       | (DEBUG) - running a tasker tick...
sonic_1       | (DEBUG) - scanning for kv store pool items to janitor
sonic_1       | (INFO) - done scanning for kv store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for fst store pool items to janitor
sonic_1       | (INFO) - done scanning for fst store pool items to janitor, expired 0 items, now has 0 items
sonic_1       | (DEBUG) - scanning for kv store pool items to flush to disk
sonic_1       | (INFO) - no kv store pool items need to be flushed at the moment
sonic_1       | (DEBUG) - scanning for fst store pool items to consolidate
sonic_1       | (INFO) - no fst store pool items to consolidate in register
sonic_1       | (INFO) - ran tasker tick (took 0s + 0ms)
```

thanks for taking a look at this!

**Comment by iodrift** [comment]
The password is correctly / identically entered in both places.

Specifying it within the sonic.cfg file did not fix it, either.
