### ISSUE TITLE
Bug: ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by luigibozzo** [ArchiveBox/ArchiveBox#1322]
#### Describe the bug

The `init --setup` fails with 
```
ModuleNotFoundError: No module named 'six'

```

#### Steps to reproduce

* follow install instruction using python pip package manager. (pip install, create folder, cd into folder)
* run `archivebox init --setup`
* you get back
```
...
ModuleNotFoundError: No module named 'six'

```

#### Screenshots or log output

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/archivebox", line 5, in <module>
    from archivebox.cli import main
  File "/opt/homebrew/lib/python3.9/site-packages/archivebox/cli/__init__.py", line 83, in <module>
    SUBCOMMANDS = list_subcommands()
  File "/opt/homebrew/lib/python3.9/site-packages/archivebox/cli/__init__.py", line 43, in list_subcommands
    module = import_module('.archivebox_{}'.format(subcommand), __package__)
  File "/opt/homebrew/Cellar/python@3.9/3.9.18/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/homebrew/lib/python3.9/site-packages/archivebox/cli/archivebox_shell.py", line 11, in <module>
    from ..main import shell
  File "/opt/homebrew/lib/python3.9/site-packages/archivebox/main.py", line 22, in <module>
    from .parsers import (
  File "/opt/homebrew/lib/python3.9/site-packages/archivebox/parsers/__init__.py", line 17, in <module>
    from ..system import atomic_write
  File "/opt/homebrew/lib/python3.9/site-packages/archivebox/system.py", line 16, in <module>
    from .util import enforce_types, ExtendedEncoder
  File "/opt/homebrew/lib/python3.9/site-packages/archivebox/util.py", line 15, in <module>
    from dateparser import parse as dateparser
  File "/opt/homebrew/lib/python3.9/site-packages/dateparser/__init__.py", line 3, in <module>
    from .date import DateDataParser
  File "/opt/homebrew/lib/python3.9/site-packages/dateparser/date.py", line 7, in <module>
    from dateutil.relativedelta import relativedelta
  File "/opt/homebrew/lib/python3.9/site-packages/dateutil/relativedelta.py", line 8, in <module>
    from six import integer_types
```

#### ArchiveBox version

0.7.2

**Comment by luigibozzo** [comment]
tried fixing (with no luck) with:
* pip install six (also with pip3, also with --ingore-installed)
* sudo pip install six (also with pip3, also with --ignore-installed)
* brew install six

**Comment by pirate** [comment]
Are you able to run other python3 programs that rely on dateparser?

```bash
$ python3

>>> from dateparser import dateparser
```

If that fails then it's some setup issue with your python install, you may need to reinstall python / try a different python version / troubleshoot over on the dateparser repo.

**Comment by pirate** [comment]
Closing this as it's not technically an ArchiveBox issue, but if you comment back here I'll still see it and I'm happy to keep providing help with fixing your python setup.
