### ISSUE TITLE
Bug: Server Error (500)

### ISSUE THREAD

**Issue by gerroon** [ArchiveBox/ArchiveBox#1325]
I just did a docker pull and the server is now inaccessible, bear in mind this was accessible and functioning prior to this pull.

```

WARNING: Some networks were defined but are not used by any service: dns
0.7.3
ArchiveBox v0.7.3+editable COMMIT_HASH=8e03755 BUILD_TIME=2024-01-15 20:39:22 1705351162
IN_DOCKER=True IN_QEMU=False ARCH=x86_64 OS=Linux PLATFORM=Linux-5.14.0-4-amd64-x86_64-with-glibc2.36 PYTHON=Cpython
FS_ATOMIC=True FS_REMOTE=True FS_USER=1000:1000 FS_PERMS=644
DEBUG=False IS_TTY=True TZ=UTC SEARCH_BACKEND=sonic LDAP=False

[i] Dependency versions:
 √  PYTHON_BINARY         v3.11.7         valid     /usr/local/bin/python3.11
 √  SQLITE_BINARY         v2.6.0          valid     /usr/local/lib/python3.11/sqlite3/dbapi2.py
 √  DJANGO_BINARY         v3.1.14         valid     /usr/local/lib/python3.11/site-packages/django/__init__.py
 √  ARCHIVEBOX_BINARY     v0.7.3          valid     /usr/local/bin/archivebox

 √  CURL_BINARY           v8.5.0          valid     /usr/bin/curl
 √  WGET_BINARY           v1.21.3         valid     /usr/bin/wget
 √  NODE_BINARY           v20.11.0        valid     /usr/bin/node
 √  SINGLEFILE_BINARY     v1.1.46         valid     /app/node_modules/single-file-cli/single-file
 √  READABILITY_BINARY    v0.0.11         valid     /app/node_modules/readability-extractor/readability-extractor
 √  MERCURY_BINARY        v1.0.0          valid     /app/node_modules/@postlight/parser/cli.js
 √  GIT_BINARY            v2.39.2         valid     /usr/bin/git
 √  YOUTUBEDL_BINARY      v2023.12.30     valid     /usr/local/bin/yt-dlp
 √  CHROME_BINARY         v120.0.6099.28  valid     /usr/bin/chromium-browser
 √  RIPGREP_BINARY        v13.0.0         valid     /usr/bin/rg

[i] Source-code locations:
 √  PACKAGE_DIR           23 files        valid     /app/archivebox
 √  TEMPLATES_DIR         3 files         valid     /app/archivebox/templates
 -  CUSTOM_TEMPLATES_DIR  -               disabled  None

[i] Secrets locations:
 -  CHROME_USER_DATA_DIR  -               disabled  None
 -  COOKIES_FILE          -               disabled  None

[i] Data locations:
 √  OUTPUT_DIR            11 files @      valid     /data
 √  SOURCES_DIR           254 files       valid     ./sources
 √  LOGS_DIR              1 files         valid     ./logs
 √  ARCHIVE_DIR           170 files       valid     ./archive
 √  CONFIG_FILE           554.0 Bytes     valid     ./ArchiveBox.conf
 √  SQL_INDEX             2.2 MB          valid     ./index.sqlite3

```

```
archivebox_1  |
archivebox_1  | System check identified no issues (0 silenced).
archivebox_1  | January 16, 2024 - 03:34:54
archivebox_1  | Django version 3.1.14, using settings 'core.settings'
archivebox_1  | Starting development server at http://0.0.0.0:8000/
archivebox_1  | Quit the server with CONTROL-C.
archivebox_1  | Internal Server Error: /admin/core/snapshot/
archivebox_1  | Traceback (most recent call last):
archivebox_1  |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
archivebox_1  |     response = get_response(request)
archivebox_1  |                ^^^^^^^^^^^^^^^^^^^^^
archivebox_1  |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
archivebox_1  |     response = response.render()
archivebox_1  |                ^^^^^^^^^^^^^^^^^
archivebox_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/response.py", line 105, in render
archivebox_1  |     self.content = self.rendered_content
archivebox_1  |                    ^^^^^^^^^^^^^^^^^^^^^
archivebox_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/response.py", line 83, in rendered_content
archivebox_1  |     return template.render(context, self._request)
archivebox_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
archivebox_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
archivebox_1  |     return self.template.render(context)
archivebox_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
archivebox_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 170, in render
archivebox_1  |     return self._render(context)
archivebox_1  |            ^^^^^^^^^^^^^^^^^^^^^
archivebox_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 162, in _render
archivebox_1  |     return self.nodelist.render(context)
archivebox_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
archivebox_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 938, in render
archivebox_1  |     bit = node.render_annotated(context)
archivebox_1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
archivebox_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 905, in render_annotated
archivebox_1  |     return self.render(context)
archivebox_1  |            ^^^^^^^^^^^^^^^^^^^^
archivebox_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/loader_tags.py", line 150, in render
archivebox_1  |     return compiled_parent._render(context)

.................
...............
rchivebox_1  |     bit = node.render_annotated(context)
archivebox_1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
archivebox_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 905, in render_annotated
archivebox_1  |     return self.render(context)
archivebox_1  |            ^^^^^^^^^^^^^^^^^^^^
archivebox_1  |   File "/usr/local/lib/python3.11/site-packages/django/template/defaulttags.py", line 446, in render
archivebox_1  |     url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
archivebox_1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
archivebox_1  |   File "/usr/local/lib/python3.11/site-packages/django/urls/base.py", line 87, in reverse
archivebox_1  |     return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
archivebox_1  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
archivebox_1  |   File "/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py", line 689, in _reverse_with_prefix
archivebox_1  |     raise NoReverseMatch(msg)
archivebox_1  | django.urls.exceptions.NoReverseMatch: Reverse for 'Docs' with keyword arguments '{'target': '_blank', 'rel': 'noopener noreferrer'}' not found. 1 pattern(s) tried: ['docs/\\Z']



```

**Comment by svcvit** [comment]
I made the same mistake as you.

**Comment by gerroon** [comment]
Yes the latest release works, this was a dev docker build

**Comment by pirate** [comment]
Fixed, thanks. https://github.com/ArchiveBox/ArchiveBox/commit/f839f4f16efe027ac2928703ab51fd7cbf0cfe1d

Was caused by small mistake in a recent PR https://github.com/ArchiveBox/ArchiveBox/pull/1323
