### ISSUE TITLE
Support: How to restore accidentally deleted `docker-compose.yml` file

### ISSUE THREAD

**Issue by satonotdead** [ArchiveBox/ArchiveBox#1436]
I accidentally removed my docker-compose files. While I can start from scratch, I have many archived pages that I want to preserve and transfer to my new instance.

What's the best way to achieve this?

My container is currently resetting itself due to missing Chrome credentials. However, I believe the archived files are still present, as I haven't deleted the Docker library folder or the persistent data bound in the docker-compose file.

**Comment by pirate** [comment]
No special procedure is needed to recover if your data/ folder is intact, simply restart the container with the same version you were using before and it should start up as usual. 

(Don't use `dev:` right now, stick to `:stable`)

**Comment by satoshinotdead** [comment]
Great, thanks!

And what about moving ArchiveBox to another server? That's why I'm trying to re-enable it first, just to ensure everything is properly archived.

**Comment by pirate** [comment]
Nothing special needed, just move the `data/` folder and `docker-compose.yml`, all the application state is inside `data/`.

**Comment by satoshinotdead** [comment]
Nice, thanks! But I'm still can't enter to the instance in order to verify if everything is OK.

How can I deal with this, when there is no `docker-compose.yml` or possibility to enter into the container because it's restarting itself?

```
AttributeError: 'PosixPath' object has no attribute 'split'
[i] [2024-05-31 15:12:56] ArchiveBox v0.7.3: archivebox server --quick-init 0.0.0.0:8000
    > /data

[X] Could not find profile "Default" in CHROME_USER_DATA_DIR.
    /data/personas/Default/chromium
    Make sure you set it to a Chrome user data directory containing a Default profile folder.
    For more info see:
        https://github.com/ArchiveBox/ArchiveBox/wiki/Configuration#CHROME_USER_DATA_DIR

    Try removing /Default from the end e.g.:
Traceback (most recent call last):
  File "/usr/local/bin/archivebox", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/archivebox/cli/__init__.py", line 140, in main
    run_subcommand(
  File "/app/archivebox/cli/__init__.py", line 74, in run_subcommand
    setup_django(in_memory_db=subcommand in fake_db, check_db=cmd_requires_db and not init_pending)
  File "/app/archivebox/config.py", line 1390, in setup_django
    check_system_config()
  File "/app/archivebox/config.py", line 1298, in check_system_config
    stderr('        CHROME_USER_DATA_DIR="{}"'.format(config['CHROME_USER_DATA_DIR'].split('/Default')[0]))
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PosixPath' object has no attribute 'split'
```
I tried to modify Archivebox.conf adding the variable `CHROME_BINARY = /usr/bin/chromium archivebox version` but it didn't work.

**Comment by pirate** [comment]
It looks like you're on an unstable dev build, can you change the `docker-compose.yml` image line to use `image: archivebox/archivebox:stable`, then `docker compose pull` and try again?

Make

**Comment by satoshinotdead** [comment]
Unfortunately, I lost my `docker-compose.yml` file. Is there a way to change the image within the container?

Thank you again. I'm also moving the files to a new instance, which might be enough.

**Comment by pirate** [comment]
I'm not sure I follow, the "container" itself is ephemeral, there is nothing kept between runs other than whats in `./data`.

If you don't have a docker-compose file then there is nothing to change, just use `docker run ... archivebox/archivebox:stable ...` next time you start it on the command line.
