### ISSUE TITLE
Bug: ...module 'os' has no attribute 'getuid' on Windows 11

### ISSUE THREAD

**Issue by digfish** [ArchiveBox/ArchiveBox#1487]
#### Describe the bug
Trying to install archivebox on a virtualenv under windows, it drops a fatal error
#### Steps to reproduce
Created a virtualenv in windows 11 running with Python 3.10.8 on Anaconda distro:
1. virtualenv archivebox
2. activate the virtualenv ( `archivebox\bin\activate`)
3. pip install archivebox
4. cd into archivebox subdir
5. mkdir data
6. cd data
7. once inside 'data': do `archivebox init --setup`
8. the error occurs (see output bellow):

#### Screenshots or log output

```
(archivebox) λ archivebox init --setup
Traceback (most recent call last):
  File "D:\libs\python-miniconda\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\libs\python-miniconda\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\venvs\archivebox\Scripts\archivebox.exe\__main__.py", line 4, in <module>
  File "D:\venvs\archivebox\lib\site-packages\archivebox\cli\__init__.py", line 11, in <module>
    from ..config import OUTPUT_DIR, check_data_folder, check_migrations
  File "D:\venvs\archivebox\lib\site-packages\archivebox\config.py", line 64, in <module>
    'PUID':                     {'type': int,   'default': os.getuid()},
AttributeError: module 'os' has no attribute 'getuid'. Did you mean: 'getpid'?
```

#### ArchiveBox version

Can't get the archivebox to execute `archivebox` without spitting the same error, used `pip freeze | grep archivebox` which gave me * 0.7.2 * .

**Comment by pirate** [comment]
Windows without WSL2/Docker is not supported.
