### ISSUE TITLE
Podman Compose doesn't support dockerfile_inline used for `sonic` config auto-download

### ISSUE THREAD

**Issue by parkerlreed** [ArchiveBox/ArchiveBox#1579]
I am able to run the init with podman compose but trying to start the server (with `docker compose up` (alias for podman compose)) in the same folder gives me this error.

Podman is running as a system service and not rootless.

```
[parker@thinknas archivebox]$ ls -lah
total 24K
drwxr-xr-x  3 parker parker 4.0K Nov  1 13:47 .
drwx------ 17 parker parker 4.0K Nov  1 13:36 ..
drwxr-xr-x  5 100910 100910 4.0K Nov  1 13:48 data
-rw-r--r--  1 parker parker 9.8K Nov  1 13:47 docker-compose.yml
[parker@thinknas archivebox]$ docker compose up
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
>>>> Executing external compose provider "/usr/bin/podman-compose". Please see podman-compose(1) for how to disable this message. <<<<

Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/podman_compose.py", line 3504, in main
    asyncio.run(async_main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/podman_compose.py", line 3500, in async_main
    await podman_compose.run()
  File "/usr/lib/python3.12/site-packages/podman_compose.py", line 1743, in run
    retcode = await cmd(self, args)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/podman_compose.py", line 2465, in compose_up
    if await compose.commands["build"](compose, build_args) != 0:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/podman_compose.py", line 2422, in compose_build
    s = await t
        ^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 631, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/podman_compose.py", line 2373, in build_one
    raise OSError("Dockerfile not found in " + ctx)
OSError: Dockerfile not found in /home/parker/.local/share/archivebox
Error: executing /usr/bin/podman-compose up: exit status 1
```

**Comment by parkerlreed** [comment]
The dockerfile inline for sonic seems to be causing this https://github.com/containers/podman-compose/issues/1065

**Comment by pirate** [comment]
I build a custom sonic container that includes the config file, `dockerfile_inline` is no longer needed:

- https://github.com/ArchiveBox/ArchiveBox/commit/6448968952b3d7f94c18ce1da4bee305c7e05f86
- https://hub.docker.com/r/archivebox/sonic
