### ISSUE TITLE
Documenting native Windows support without WSL or WSL2

### ISSUE THREAD

**Issue by umairsiddiqui-digitek** [ArchiveBox/ArchiveBox#532]
hi,
following the README, i performed following (on windows)
```
python -m venv venv
venv\Scripts\activate.bat
 mkdir data
cd data
pip install archivebox
archivebox init
```

but i am getting following error

```

←[01;31m[X] Error while loading configuration value: WGET_AUTO_COMPRESSION←[00;00m
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    Check your config for mistakes and try again (your archive data is unaffected).

    For config documentation and examples see:
        https://github.com/pirate/ArchiveBox/wiki/Configuration

Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\data_dir\bookmarks\venv\Scripts\archivebox.exe\__main__.py", line 5, in <module>
  File "d:\data_dir\bookmarks\venv\lib\site-packages\archivebox\cli\__init__.py", line 10, in <module>
    from ..config import OUTPUT_DIR
  File "d:\data_dir\bookmarks\venv\lib\site-packages\archivebox\config\__init__.py", line 778, in <module>
    CONFIG = load_all_config()
  File "d:\data_dir\bookmarks\venv\lib\site-packages\archivebox\config\__init__.py", line 776, in load_all_config
    return load_config(DERIVED_CONFIG_DEFAULTS, CONFIG)
  File "d:\data_dir\bookmarks\venv\lib\site-packages\archivebox\config\__init__.py", line 444, in load_config
    extended_config[key] = load_config_val(
  File "d:\data_dir\bookmarks\venv\lib\site-packages\archivebox\config\__init__.py", line 321, in load_config_val
    return default(config)
  File "d:\data_dir\bookmarks\venv\lib\site-packages\archivebox\config\__init__.py", line 256, in <lambda>
    'WGET_AUTO_COMPRESSION':    {'default': lambda c: wget_supports_compression(c) if c['USE_WGET'] else False},
  File "d:\data_dir\bookmarks\venv\lib\site-packages\archivebox\config\__init__.py", line 608, in wget_supports_compression
    return not run(cmd, stdout=DEVNULL, stderr=DEVNULL).returncode
  File "C:\Python38\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

my  requirements.txt contains:
```
archivebox==0.4.21
asgiref==3.3.1
atomicwrites==1.4.0
backcall==0.2.0
base32-crockford==0.3.0
certifi==2020.11.8
chardet==3.0.4
colorama==0.4.4
croniter==0.3.34
dateparser==1.0.0
decorator==4.4.2
Django==3.0.8
django-extensions==3.0.3
idna==2.10
ipython==7.19.0
ipython-genutils==0.2.0
jedi==0.17.2
mypy-extensions==0.4.3
natsort==7.0.1
parso==0.7.1
pickleshare==0.7.5
prompt-toolkit==3.0.8
Pygments==2.7.2
python-crontab==2.5.1
python-dateutil==2.8.1
pytz==2020.4
regex==2020.11.11
requests==2.24.0
six==1.15.0
sqlparse==0.4.1
traitlets==5.0.5
tzlocal==2.1
urllib3==1.25.11
w3lib==1.22.0
wcwidth==0.2.5
wget==3.2
youtube-dl==2020.11.12

```

**Comment by umairsiddiqui-digitek** [comment]
ok i downloaded wget for windows from

```
https://eternallybored.org/misc/wget/1.20.3/64/wget.exe
```
now init command is working. maybe update README for windows case? 

```
D:\data_dir\bookmarks\data
(venv) λ archivebox init
[X] Unable to find a working version of Chrome/Chromium, is it installed and in your $PATH?

←[01;30m[i] [2020-11-12 11:00:44] ArchiveBox v0.4.21: archivebox init←[00;00m
←[01;30m    > D:\data_dir\bookmarks\data←[00;00m

←[01;32m[+] Initializing a new ArchiveBox collection in this folder...←[00;00m
    D:\data_dir\bookmarks\data
←[01;32m------------------------------------------------------------------←[00;00m

←[01;32m[+] Building archive folder structure...←[00;00m
    √ D:\data_dir\bookmarks\data\sources
    √ D:\data_dir\bookmarks\data\archive
    √ D:\data_dir\bookmarks\data\logs
←[01;31m[X] Unable to find a working version of Chrome/Chromium, is it installed and in your $PATH?←[00;00m

    √ D:\data_dir\bookmarks\data\ArchiveBox.conf

←[01;32m[+] Building main SQL index and running migrations...←[00;00m
[X] Unable to find a working version of Chrome/Chromium, is it installed and in your $PATH?

    √ D:\data_dir\bookmarks\data\index.sqlite3

    Operations to perform:
    Apply all migrations: admin, auth, contenttypes, core, sessions
    Running migrations:
    Applying contenttypes.0001_initial... OK
    Applying auth.0001_initial... OK
    Applying admin.0001_initial... OK
    Applying admin.0002_logentry_remove_auto_add... OK
    Applying admin.0003_logentry_add_action_flag_choices... OK
    Applying contenttypes.0002_remove_content_type_name... OK
    Applying auth.0002_alter_permission_name_max_length... OK
    Applying auth.0003_alter_user_email_max_length... OK
    Applying auth.0004_alter_user_username_opts... OK
    Applying auth.0005_alter_user_last_login_null... OK
    Applying auth.0006_require_contenttypes_0002... OK
    Applying auth.0007_alter_validators_add_error_messages... OK
    Applying auth.0008_alter_user_username_max_length... OK
    Applying auth.0009_alter_user_last_name_max_length... OK
    Applying auth.0010_alter_group_name_max_length... OK
    Applying auth.0011_update_proxy_permissions... OK
    Applying core.0001_initial... OK
    Applying core.0002_auto_20200625_1521... OK
    Applying core.0003_auto_20200630_1034... OK
    Applying core.0004_auto_20200713_1552... OK
    Applying core.0005_auto_20200728_0326... OK
    Applying sessions.0001_initial... OK

←[01;32m[*] Collecting links from any existing indexes and archive folders...←[00;00m

←[01;30m[*] [2020-11-12 11:00:53] Writing 0 links to main index...←[00;00m

    √ D:\data_dir\bookmarks\data\index.sqlite3

    √ D:\data_dir\bookmarks\data\index.json

    √ D:\data_dir\bookmarks\data\index.html

←[01;32m------------------------------------------------------------------←[00;00m
←[01;32m[√] Done. A new ArchiveBox collection was initialized (0 links).←[00;00m

    ←[01;35mHint:←[00;00m To view your archive index, run:
        archivebox server  # then visit http://127.0.0.1:8000

    To add new links, you can run:
        archivebox add ~/some/path/or/url/to/list_of_links.txt

    For more usage and examples, run:
        archivebox help
```

**Comment by pirate** [comment]
I'm assuming this is in the WSL2, or did you run this directly on windows? If so that's quite surprising, last I checked there were a number of blockers preventing it from working.

**Comment by umairsiddiqui-digitek** [comment]
I was actually running it on windows7, so no wsl. Then I switched to docker. Didn't check on win10

**Comment by pirate** [comment]
Closing this for now as I'm no longer officially supporting WSL/WSL2, Docker is now the only official install method for windows.

I'm sure some people will figure out how to run it on Windows and I hope they share their results, but I don't own a Windows machine and don't know Windows well enough to support it myself officially.
