### ISSUE TITLE
Bugfix: init not working

### ISSUE THREAD

**Issue by ekiel** [ArchiveBox/ArchiveBox#558]
ArchiveBox says the collection needs to be upgraded via archivebox init

#### Describe the bug
Updated to archivebox/archivebox:latest and container tells me to upgrade:
```
[X] This collection was created with an older version of ArchiveBox and must be upgraded first.
    /data

    To upgrade it to the latest version and apply the 1 pending migrations run:
        archivebox init
```
#### Steps to reproduce
ran docker-compose run archivebox init and I get the following error:

#### Screenshots or log output

```
*] Updating existing ArchiveBox collection in this folder...
    /data
------------------------------------------------------------------

[*] Verifying archive folder structure...
    √ /data/sources
    √ /data/archive
    √ /data/logs
    √ /data/ArchiveBox.conf

[*] Verifying main SQL index and running migrations...
    √ /data/index.sqlite3

Traceback (most recent call last):
  File "/usr/local/bin/archivebox", line 33, in <module>
    sys.exit(load_entry_point('archivebox', 'console_scripts', 'archivebox')())
  File "/app/archivebox/cli/__init__.py", line 123, in main
    run_subcommand(
  File "/app/archivebox/cli/__init__.py", line 63, in run_subcommand
    module.main(args=subcommand_args, stdin=stdin, pwd=pwd)    # type: ignore
  File "/app/archivebox/cli/archivebox_init.py", line 33, in main
    init(
  File "/app/archivebox/util.py", line 113, in typechecked_function
    return func(*args, **kwargs)
  File "/app/archivebox/main.py", line 317, in init
    for migration_line in apply_migrations(out_dir):
  File "/app/archivebox/util.py", line 113, in typechecked_function
    return func(*args, **kwargs)
  File "/app/archivebox/index/sql.py", line 102, in apply_migrations
    call_command("migrate", interactive=False, stdout=out)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 168, 
in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 371, in e
xecute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 85, in wr
apped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", li
ne 243, in handle
    post_migrate_state = executor.migrate(
   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in
 migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_in
itial)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in
 _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 227, in
 apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/migration.py", line 124, i
n apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/operations/special.py", li
ne 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/app/archivebox/core/migrations/0007_archiveresult.py", line 33, in forwards_func
    ArchiveResult.objects.create(extractor=extractor, snapshot=snapshot, cmd=result["cmd"], cm
d_version=result["cmd_version"], 
KeyError: 'cmd_version'
```

#### Software versions

 - OS: POP_OS! 20.10/Docker version 19.03.13, build 4484c46/Docker-compose 1.25
 - ArchiveBox version: archivebox/archivebox:ed54df499e2e477b5d7b98e0f3479ecba3bfe44a and :latest

**Comment by pirate** [comment]
Do not use the `latest` container, it's based on `master` and is not stable. You should only use one of the tagged versions like `0.4.21`.

**Comment by ekiel** [comment]
Thanks! I wasn't able to revert back to 0.4.21 (it said my /data directory had to be empty, but I went back to nikisweeting/archivebox:a1cd8a5217ec4205e86a1bc7b8e51b4bd5b0c938 and it worked to get me back up and running! I'll be patient as you guys work on this!

Keep up the amazing work!
