### ISSUE TITLE
Bugfix: ModuleNotFoundError: No module named 'archivebox.vendor.base32_crockford'

### ISSUE THREAD

**Issue by CalebUsadi** [ArchiveBox/ArchiveBox#613]
#### Describe the bug

Since updating from 0.4.24-1 to 0.5.3-1, whenever I run `archivebox`, or an command following it, I get the error `ModuleNotFoundError: No module named 'archivebox.vendor.base32_crockford'`. I didn't have this issue before, and I'm unable to revert back to the earlier version. May be related to https://github.com/ArchiveBox/ArchiveBox/issues/581.

#### Steps to reproduce

1. Install archivebox .
2. Run any archivebox command, e.g. `archivebox --version`, `archivebox init`.
3. Receive below error.

#### Screenshots or log output

```
Traceback (most recent call last):
  File "/usr/bin/archivebox", line 11, in <module>
    load_entry_point('archivebox==0.5.3', 'console_scripts', 'archivebox')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/archivebox/cli/__init__.py", line 72, in <module>
    SUBCOMMANDS = list_subcommands()
  File "/usr/lib/python3/dist-packages/archivebox/cli/__init__.py", line 44, in list_subcommands
    module = import_module('.archivebox_{}'.format(subcommand), __package__)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3/dist-packages/archivebox/cli/archivebox_add.py", line 11, in <module>
    from ..main import add
  File "/usr/lib/python3/dist-packages/archivebox/main.py", line 22, in <module>
    from .parsers import (
  File "/usr/lib/python3/dist-packages/archivebox/parsers/__init__.py", line 17, in <module>
    from ..system import atomic_write
  File "/usr/lib/python3/dist-packages/archivebox/system.py", line 15, in <module>
    from .util import enforce_types, ExtendedEncoder
  File "/usr/lib/python3/dist-packages/archivebox/util.py", line 18, in <module>
    from .vendor.base32_crockford import encode as base32_encode                            # type: ignore
ModuleNotFoundError: No module named 'archivebox.vendor.base32_crockford'
```

#### Software versions

 - OS:                       Ubuntu 20.04.1 LTS 64-bit
 - ArchiveBox version:        archivebox/focal,focal,now 0.5.3-1
 - Python version:            Python 3.8.5

**Comment by pirate** [comment]
Thanks for reporting. Try now, I fixed a problem with the debian packaging process and bumped it to `0.5.3-2`.

**Comment by CalebUsadi** [comment]
Thank you! Trying to update with `apt` didn't yet give me an update. In retrospect I realized that I had added `ppa:archivebox/archivebox` to my `apt` sources instead of just using the recommended installation method, can't find in the docs why I might have done that. I uninstalled archivebox with `apt` and reinstalled with `python3 -m pip install --upgrade archivebox`. Worked perfectly.

**Comment by sistein** [comment]
Any expectations when 0.5.3-2 will be available via apt? 

I would prefer to change to the more simple apt installation and 0.5.3-1 is still delivered there.

**Comment by pirate** [comment]
oh we're already on 0.5.4 at this point, just `apt update; apt upgrade archivebox`

**Comment by sistein** [comment]
@pirate looks like the build is failing => No update via apt upgrade 

https://launchpad.net/~archivebox/+archive/ubuntu/archivebox/+build/20962645

**Comment by pirate** [comment]
Looks like Debian changed the build tool they use on their servers from dh-python to pybuild, which broke my build :(

You can install via `pip` or `dpkg` for now until I fix it.

**Comment by pirate** [comment]
Build is passing, try now: https://launchpad.net/~archivebox/+archive/ubuntu/archivebox/+build/21002060
