### ISSUE TITLE
NodeNotFoundError: Migration core.0018_auto_20210327_0603 dependencies reference nonexistent parent node

### ISSUE THREAD

**Issue by Leontking** [ArchiveBox/ArchiveBox#682]
```
E:\ArchiveBox> archivebox init
[i] [2021-03-30 03:55:43] ArchiveBox v0.5.4: archivebox init
    > E:\ArchiveBox

[+] Initializing a new ArchiveBox collection in this folder...
    E:\ArchiveBox
------------------------------------------------------------------

[+] Building archive folder structure...
    √ E:\ArchiveBox\sources
    √ E:\ArchiveBox\archive
    √ E:\ArchiveBox\logs
    √ E:\ArchiveBox\ArchiveBox.conf

[+] Building main SQL index and running migrations...
    √ E:\ArchiveBox\index.sqlite3

Traceback (most recent call last):
  File "d:\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Python\Scripts\archivebox.exe\__main__.py", line 7, in <module>
    from .cli import main
  File "d:\python\lib\site-packages\archivebox\cli\__init__.py", line 129, in main
    run_subcommand(
  File "d:\python\lib\site-packages\archivebox\cli\__init__.py", line 69, in run_subcommand
    module.main(args=subcommand_args, stdin=stdin, pwd=pwd)    # type: ignore
  File "d:\python\lib\site-packages\archivebox\cli\archivebox_init.py", line 33, in main
    init(
  File "d:\python\lib\site-packages\archivebox\util.py", line 112, in typechecked_function
    return func(*args, **kwargs)
  File "d:\python\lib\site-packages\archivebox\main.py", line 323, in init
    for migration_line in apply_migrations(out_dir):
  File "d:\python\lib\site-packages\archivebox\util.py", line 112, in typechecked_function
    return func(*args, **kwargs)
  File "d:\python\lib\site-packages\archivebox\index\sql.py", line 97, in apply_migrations
    call_command("makemigrations", interactive=False, stdout=null)
  File "d:\python\lib\site-packages\django\core\management\__init__.py", line 168, in call_command
    return command.execute(*args, **defaults)
  File "d:\python\lib\site-packages\django\core\management\base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "d:\python\lib\site-packages\django\core\management\base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "d:\python\lib\site-packages\django\core\management\commands\makemigrations.py", line 87, in handle
    loader = MigrationLoader(None, ignore_no_migrations=True)
  File "d:\python\lib\site-packages\django\db\migrations\loader.py", line 53, in __init__
    self.build_graph()
  File "d:\python\lib\site-packages\django\db\migrations\loader.py", line 255, in build_graph
    self.graph.validate_consistency()
  File "d:\python\lib\site-packages\django\db\migrations\graph.py", line 195, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "d:\python\lib\site-packages\django\db\migrations\graph.py", line 195, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "d:\python\lib\site-packages\django\db\migrations\graph.py", line 58, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration core.0018_auto_20210327_0603 dependencies reference nonexistent parent node ('core', '0017_auto_20210219_0211')
```

**Comment by pirate** [comment]
```
pip3 uninstall archivebox
pip3 install "git+https://github.com/ArchiveBox/ArchiveBox.git@dev"
archivebox init
```
