### ISSUE TITLE
Bug: archivebox init returns a ValueError

### ISSUE THREAD

**Issue by h05hardman** [ArchiveBox/ArchiveBox#738]
When I run `archivebox init`, I get a ValueError.

#### Describe the bug
I installed archivebox via pacman.
I expected it to give some output about confirming archivebox was initialized cerrectly or something, but I just got a ValueError.

#### Screenshots or log output
```logs
[me@desktop WebArchive]$ archivebox init
/home/me/.local/lib/python3.9/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.1) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
[i] [2021-05-04 15:34:18] ArchiveBox v0.6.2: archivebox init
    > /home/me/WebArchive

Traceback (most recent call last):
  File "/usr/bin/archivebox", line 33, in <module>
    sys.exit(load_entry_point('archivebox==0.6.2', 'console_scripts', 'archivebox')())
  File "/usr/lib/python3.9/site-packages/archivebox/cli/__init__.py", line 140, in main
    run_subcommand(
  File "/usr/lib/python3.9/site-packages/archivebox/cli/__init__.py", line 74, in run_subcommand
    setup_django(in_memory_db=subcommand in fake_db, check_db=cmd_requires_db and not init_pending)
  File "/usr/lib/python3.9/site-packages/archivebox/config.py", line 1136, in setup_django
    django.setup()
  File "/usr/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/lib/python3.9/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/archivebox/core/models.py", line 87, in <module>
    class Snapshot(models.Model):
  File "/usr/lib/python3.9/site-packages/django/db/models/base.py", line 161, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/usr/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/lib/python3.9/site-packages/django/db/models/fields/related.py", line 1635, in contribute_to_class
    self.remote_field.through = create_many_to_many_intermediary_model(self, cls)
  File "/usr/lib/python3.9/site-packages/django/db/models/fields/related.py", line 1104, in create_many_to_many_intermediary_model
    return type(name, (models.Model,), {
  File "/usr/lib/python3.9/site-packages/django/db/models/base.py", line 320, in __new__
    new_class._prepare()
  File "/usr/lib/python3.9/site-packages/django/db/models/base.py", line 333, in _prepare
    opts._prepare(cls)
  File "/usr/lib/python3.9/site-packages/django/db/models/options.py", line 285, in _prepare
    pk_class = self._get_default_pk_class()
  File "/usr/lib/python3.9/site-packages/django/db/models/options.py", line 246, in _get_default_pk_class
    raise ValueError(
ValueError: Primary key 'django.db.models.UUIDField' referred by core.apps.CoreConfig.default_auto_field must subclass AutoField.
```

#### ArchiveBox version

```logs
ArchiveBox v0.6.2
Cpython Linux Linux-5.9.16-1-MANJARO-x86_64-with-glibc2.33 x86_64
IN_DOCKER=False DEBUG=False IS_TTY=True TZ=UTC SEARCH_BACKEND_ENGINE=ripgrep

[i] Dependency versions:
 √  ARCHIVEBOX_BINARY     v0.6.2          valid     /usr/bin/archivebox                                                         
 √  PYTHON_BINARY         v3.9.4          valid     /usr/bin/python3.9                                                          
 √  DJANGO_BINARY         v3.2.0          valid     /usr/lib/python3.9/site-packages/django/bin/django-admin.py                 
 √  CURL_BINARY           v7.76.1         valid     /usr/bin/curl                                                               
 √  WGET_BINARY           v1.21.1         valid     /usr/bin/wget                                                               
 √  NODE_BINARY           v16.0.0         valid     /usr/bin/node                                                               
 √  SINGLEFILE_BINARY     v0.3.19         valid     /opt/single-file/cli/single-file                                            
 √  READABILITY_BINARY    v0.0.2          valid     /usr/lib/node_modules/readability-extractor/readability-extractor           
 √  MERCURY_BINARY        v1.0.0          valid     /usr/lib/node_modules/@postlight/mercury-parser/cli.js                      
 √  GIT_BINARY            v2.31.1         valid     /usr/bin/git                                                                
 √  YOUTUBEDL_BINARY      v2021.04.26     valid     /usr/bin/youtube-dl                                                         
 √  CHROME_BINARY         v90.0.4430.93   valid     /usr/bin/chromium                                                           
 √  RIPGREP_BINARY        v12.1.1         valid     /usr/bin/rg                                                                 

[i] Source-code locations:
 √  PACKAGE_DIR           23 files        valid     /usr/lib/python3.9/site-packages/archivebox                                 
 √  TEMPLATES_DIR         3 files         valid     /usr/lib/python3.9/site-packages/archivebox/templates                       
 -  CUSTOM_TEMPLATES_DIR  -               disabled                                                                              

[i] Secrets locations:
 -  CHROME_USER_DATA_DIR  -               disabled                                                                              
 -  COOKIES_FILE          -               disabled                                                                              


[i] Data locations:

```

**Comment by pirate** [comment]
`pip3 install django==3.1.8`

**Comment by h05hardman** [comment]
Thanks.
After installing croniter, ipython and upgrading python-crontab which I got told as being required too, it finished initializing.
Wow. That reply was fast. When I remember of my experiences with a FetchCord Issue...
Now it works.
Thanks.
