### ISSUE TITLE
Bug: docker-compose does not start  - traceback

### ISSUE THREAD

**Issue by cjbarroso** [ArchiveBox/ArchiveBox#775]
#### Describe the bug
Following instructions for docker-compose results on the app not starting and throwing a traceback.

#### Steps to reproduce
Use docker-compose instructions:
- mkdir ~/archivebox && cd ~/archivebox
- curl -O 'https://raw.githubusercontent.com/ArchiveBox/ArchiveBox/master/docker-compose.yml'
- docker-compose run archivebox init --setup

#### Screenshots or log output

```
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/bin/docker-compose", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/compose/cli/main.py", line 13, in <module>
    import docker.errors
  File "/usr/lib/python3.9/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/lib/python3.9/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/lib/python3.9/site-packages/docker/api/client.py", line 6, in <module>
    import requests
  File "/home/charlie/.local/lib/python3.9/site-packages/requests/__init__.py", line 120, in <module>
    from . import utils
  File "/home/charlie/.local/lib/python3.9/site-packages/requests/utils.py", line 25, in <module>
    from . import certs
  File "/home/charlie/.local/lib/python3.9/site-packages/requests/certs.py", line 15, in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'
```

#### ArchiveBox version
`master` docker image (which is default on the docker-compose file) at the time of this writing, 20210628192300 UTC-3

**Comment by cjbarroso** [comment]
My local default python3 dependencies were broken, and docker was not properly initializing. Closing now.
