### ISSUE TITLE
Failed to set up development environment

### ISSUE THREAD

**Issue by anton-samal** [ArchiveBox/ArchiveBox#876]
#### Describe the bug
can't build a docker image for development. Already tried to delete the repo directory and clone it again. OS: win10

#### Steps to reproduce
As described here https://github.com/ArchiveBox/ArchiveBox#archivebox-development
1. git clone --recurse-submodules https://github.com/ArchiveBox/ArchiveBox
2. cd ArchiveBox
3. git checkout dev
4. git submodule update --init --recursive
5. git pull --recurse-submodules
6. Choose option B( Build the docker container and use that for development instead): docker build . -t archivebox

#### log output
` \=> ERROR [17/19] RUN pip install -e .                                                                                                                                                    0.7s
------
 > [17/19] RUN pip install -e .:
#21 0.436 Obtaining file:///app
#21 0.574     ERROR: Command errored out with exit status 1:
#21 0.574      command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/app/setup.py'"'"'; __file__='"'"'/app/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-fenopylh
#21 0.574          cwd: /app/
#21 0.574     Complete output (11 lines):
#21 0.574     Traceback (most recent call last):
#21 0.574       File "<string>", line 1, in <module>
#21 0.574       File "/app/setup.py", line 29, in <module>
#21 0.574         VERSION = json.loads((PACKAGE_DIR / "package.json").read_text().strip())['version']
#21 0.574       File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
#21 0.574         return _default_decoder.decode(s)
#21 0.574       File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
#21 0.574         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
#21 0.574       File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
#21 0.574         raise JSONDecodeError("Expecting value", s, err.value) from None
#21 0.574     json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
#21 0.574     ----------------------------------------
#21 0.574 WARNING: Discarding file:///app. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#21 0.574 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
\------
executor failed running [/bin/sh -c pip install -e .]: exit code: 1`

#### ArchiveBox version

dev branch

**Comment by anton-samal** [comment]
worked with WSL.
