### ISSUE TITLE
Bug: npm is not listed as a dependency

### ISSUE THREAD

**Issue by myself248** [ArchiveBox/ArchiveBox#938]
#### Describe the bug

Npm isn't listed as a dependency, but installation fails if you don't have it. 

#### Steps to reproduce

It's a fresh install on an Ubuntu 20.04 (dist-upgraded from 18.04) machine that's never had archivebox on it before, so the repro steps are exactly the install steps in the "package manager / apt / ubuntu/debian" section of the front page of archivebox.org. 

#### Screenshots or log output

Installing with apt as per instructions, everything looked normal up to this npm error: 

```[+] Installing enabled ArchiveBox dependencies automatically...

    Installing YOUTUBEDL_BINARY automatically using pip...
2021.12.17 is already installed youtube-dl

    Installing CHROME_BINARY automatically using playwright...
Chromium 98.0.4758.102 snap is already installed chromium

    Installing SINGLEFILE_BINARY, READABILITY_BINARY, MERCURY_BINARY automatically using npm...
[X] Failed to install npm packages: [Errno 2] No such file or directory: 'npm'
    Hint: Try deleting /home/user/archivebox/node_modules and running it again
```
There is no node_modules to delete, so that suggestion doesn't work. Finally I just ran "npm" to see if it would do anything, like maybe there's an npm version command whose output might be relevant here, and realized I didn't have npm installed:

```user@t460:~/archivebox$ npm

Command 'npm' not found, but can be installed with:

sudo apt install npm
```
After doing that, I reran archivebox init --setup and it installed two of the three, but singlefile still fails:

```i] Dependency versions:
 √  ARCHIVEBOX_BINARY     v0.6.2          valid     /usr/local/bin/archivebox                                                   
 √  PYTHON_BINARY         v3.8.10         valid     /usr/bin/python3.8                                                          
 √  DJANGO_BINARY         v3.1.14         valid     /usr/local/lib/python3.8/dist-packages/django/bin/django-admin.py           
 √  CURL_BINARY           v7.68.0         valid     /usr/bin/curl                                                               
 √  WGET_BINARY           v1.20.3         valid     /usr/bin/wget                                                               
 √  NODE_BINARY           v10.19.0        valid     /usr/bin/node                                                               
 X  SINGLEFILE_BINARY     ?               invalid   ./node_modules/single-file/cli/single-file                                  
 √  READABILITY_BINARY    v0.0.3          valid     ./node_modules/readability-extractor/readability-extractor                  
 √  MERCURY_BINARY        v1.0.0          valid     ./node_modules/@postlight/mercury-parser/cli.js                             
 √  GIT_BINARY            v2.25.1         valid     /usr/bin/git                                                                
 √  YOUTUBEDL_BINARY      v2021.12.17     valid     /usr/local/bin/youtube-dl                                                   
 √  CHROME_BINARY         v98.0.4758.102  valid     /snap/bin/chromium                                                          
 √  RIPGREP_BINARY        v11.0.2         valid     /usr/bin/rg         
```

manually running singlefile --version results in the following:

```
user@t460:~/archivebox/node_modules/single-file/cli$ ./single-file --version
/home/user/archivebox/node_modules/yargs/node_modules/yargs-parser/build/index.cjs:1013
        throw Error(`yargs parser supports a minimum Node.js version of ${minNodeVersion}. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions`);
        ^

Error: yargs parser supports a minimum Node.js version of 12. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions
    at Object.<anonymous> (/home/user/archivebox/node_modules/yargs/node_modules/yargs-parser/build/index.cjs:1013:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/user/archivebox/node_modules/yargs/build/index.cjs:1:58028)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

#### ArchiveBox version

this was taken before installing npm: 

```logs
ArchiveBox v0.6.2
Cpython Linux Linux-5.4.0-100-generic-x86_64-with-glibc2.29 x86_64
IN_DOCKER=False DEBUG=False IS_TTY=True TZ=UTC SEARCH_BACKEND_ENGINE=ripgrep

[i] Dependency versions:
 √  ARCHIVEBOX_BINARY     v0.6.2          valid     /usr/local/bin/archivebox                                                   
 √  PYTHON_BINARY         v3.8.10         valid     /usr/bin/python3.8                                                          
 √  DJANGO_BINARY         v3.1.14         valid     /usr/local/lib/python3.8/dist-packages/django/bin/django-admin.py           
 √  CURL_BINARY           v7.68.0         valid     /usr/bin/curl                                                               
 √  WGET_BINARY           v1.20.3         valid     /usr/bin/wget                                                               
 √  NODE_BINARY           v10.19.0        valid     /usr/bin/node                                                               
 X  SINGLEFILE_BINARY     ?               invalid   single-file                                                                 
 X  READABILITY_BINARY    ?               invalid   readability-extractor                                                       
 X  MERCURY_BINARY        ?               invalid   mercury-parser                                                              
 √  GIT_BINARY            v2.25.1         valid     /usr/bin/git                                                                
 √  YOUTUBEDL_BINARY      v2021.12.17     valid     /usr/local/bin/youtube-dl                                                   
 √  CHROME_BINARY         v98.0.4758.102  valid     /snap/bin/chromium                                                          
 √  RIPGREP_BINARY        v11.0.2         valid     /usr/bin/rg                                                                 

[i] Source-code locations:
 √  PACKAGE_DIR           23 files        valid     /usr/local/lib/python3.8/dist-packages/archivebox                           
 √  TEMPLATES_DIR         3 files         valid     /usr/local/lib/python3.8/dist-packages/archivebox/templates                 
 -  CUSTOM_TEMPLATES_DIR  -               disabled                                                                              

[i] Secrets locations:
 -  CHROME_USER_DATA_DIR  -               disabled                                                                              
 -  COOKIES_FILE          -               disabled                                                                              

[i] Data locations:
 √  OUTPUT_DIR            8 files         valid     /home/user/archivebox                                                       
 √  SOURCES_DIR           1 files         valid     ./sources                                                                   
 √  LOGS_DIR              1 files         valid     ./logs                                                                      
 √  ARCHIVE_DIR           1 files         valid     ./archive                                                                   
 √  CONFIG_FILE           81.0 Bytes      valid     ./ArchiveBox.conf                                                           
 √  SQL_INDEX             204.0 KB        valid     ./index.sqlite3                                                             

[!] Warning: Missing 3 recommended dependencies
    ! SINGLEFILE_BINARY: single-file (unable to detect version)
      Hint: To install all packages automatically run: archivebox setup
            or to disable it and silence this warning: archivebox config --set SAVE_SINGLEFILE=False
            
    ! READABILITY_BINARY: readability-extractor (unable to detect version)
      Hint: To install all packages automatically run: archivebox setup
            or to disable it and silence this warning: archivebox config --set SAVE_READABILITY=False
            
    ! MERCURY_BINARY: mercury-parser (unable to detect version)
      Hint: To install all packages automatically run: archivebox setup
            or to disable it and silence this warning: archivebox config --set SAVE_MERCURY=False

```
after installing npm, and rerunning `archivebox init --setup`, output looks the same except readability and mercury are valid, only singlefile fails:

```
 X  SINGLEFILE_BINARY     ?               invalid   ./node_modules/single-file/cli/single-file                                  
 √  READABILITY_BINARY    v0.0.3          valid     ./node_modules/readability-extractor/readability-extractor                  
 √  MERCURY_BINARY        v1.0.0          valid     ./node_modules/@postlight/mercury-parser/cli.js           
```

**Comment by pirate** [comment]
This is somewhat expected, Ubuntu's strict version pinning for apt packages makes it so the default npm install is too old to run the newest single-file version. You have to choose, do you want a newer node install and the latest and greatest single-file (add the apt repo for the latest node.js versions), or the old node + old singlefile (install them manually).

**Comment by mobilelifeful** [comment]
@pirate Can you please elaborate a bit more on "do you want a newer node install and the latest and greatest single-file (add the apt repo for the latest node.js versions), or the old node + old singlefile (install them manually)."? by giving a working solution to install them? (that you think is the best)

"same" env. set up of ubuntu. 

just found this tool, but can't get it working.  Thank you in advance.

**Comment by pirate** [comment]
Follow these instructions to install the latest version of NodeJS + NPM on Ubuntu/Debian based OS's https://github.com/nodesource/distributions#debinstall  `npm install -g npm`
