### ISSUE TITLE
Question: Trouble Running add from docker-compose command

### ISSUE THREAD

**Issue by stephenmetzger** [ArchiveBox/ArchiveBox#943]
Hi all. 

Trying to run `docker-compose run archivebox add 'http://google.com'` and getting the error:

```root@proxmoxdebian:/data/archivebox/data# docker-compose run archivebox add 'http://google.com' --rm
Creating archivebox_archivebox_run ... done
[i] [2022-03-11 04:59:59] ArchiveBox v0.6.2: archivebox add http://google.com --rm
    > /data

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 411, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: disk I/O error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/archivebox", line 33, in <module>
    sys.exit(load_entry_point('archivebox', 'console_scripts', 'archivebox')())
  File "/app/archivebox/cli/__init__.py", line 140, in main
    run_subcommand(
  File "/app/archivebox/cli/__init__.py", line 74, in run_subcommand
    setup_django(in_memory_db=subcommand in fake_db, check_db=cmd_requires_db and not init_pending)
  File "/app/archivebox/config.py", line 1152, in setup_django
    current_mode = cursor.execute("PRAGMA journal_mode")
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 411, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: disk I/O error
ERROR: 1 
```

Not sure what I'm doing wrong here.

**Comment by pirate** [comment]
It's an issue with your filesystem. Either the `data/` folder is on a failing drive, it's not writable due to permissions, it's a broken symlink, or some other problem.

**Comment by stephenmetzger** [comment]
> It's an issue with your filesystem. Either the `data/` folder is on a failing drive, it's not writable due to permissions, it's a broken symlink, or some other problem outside of ArchiveBox's control.

You are exactly right. Was running low on disk space. Freeing up space solved the problem. Thanks.

This actually brings me to another question now:

How would I set up my docker-compose.yml to use a bind mount for the appdata (ArchiveBox.conf, index.sqlite3, logs, etc) on my hosts local storage, but link the archive folder to a samba share mounted to the ArchiveBox host? Under the archivebox service, would adding a link to `/mnt/SAMBAstorage/archivebox/archive` from `/data/archive` work, or, since archive is a subdirectory of data, would this cause issues?

```    archivebox:
        # build: .                              # for developers working on archivebox
        image: ${DOCKER_IMAGE:-archivebox/archivebox:master}
        command: server --quick-init 0.0.0.0:8000
        ports:
            - 8000:8000
        environment:
            - ALLOWED_HOSTS=*                   # add any config options you want as env vars
            - MEDIA_MAX_SIZE=750m
            # - SEARCH_BACKEND_ENGINE=sonic     # uncomment these if you enable sonic below
            # - SEARCH_BACKEND_HOST_NAME=sonic
            # - SEARCH_BACKEND_PASSWORD=SecretPassword
        volumes:
            - /user/docker/archivebox/data:/data
            - /mnt/SAMBAstorage/archivebox/archive:/data/archive
 ```

**Comment by stephenmetzger** [comment]
Whelp. My fix above isn't working out. Going to close this thread since it solved by initial problem and start a new one with this new issue. 

Thanks.
